### ISSUE TITLE
User location is not supported for the API use.

### ISSUE THREAD

**Issue by jasonclong** [BrianShenCC/bob-plugin-gemini-translate#1]
error：User location is not supported for the API use.

Bob 界面报错，有人遇到这个问题吗？
wrt 全局 proxy 已经切换至 US 也不行

**Comment by BrianShenCC** [comment]
暂时遇到这个问题，我的梯子返回是正常的

**Comment by wongchenv** [comment]
有这个问题

**Comment by BrianShenCC** [comment]
这个报错信息应该是gemini自己返回的，可能本周我会出个代理模式来解决

**Comment by tosspi** [comment]
我也遇到了这个问题，有解决吗？

**Comment by BrianShenCC** [comment]
可以试试自建代理，在readme里面有链接

**Comment by jasonclong** [comment]
😂我这边更新 0.013 版本之后似乎正常了，环境没变化还是同一个 proxy

**Comment by BrianShenCC** [comment]
啥都没改。。。。
