### ISSUE TITLE
如何自定义 prompt？谢谢

### ISSUE THREAD

**Issue by yuanyuanyuan** [BrianShenCC/bob-plugin-gemini-translate#12]

**Comment by BrianShenCC** [comment]
我觉得对话模式基本可以替代自定义prompt了，就没弄。

如果提供的prompt不够理想，欢迎提pr优化

**Comment by fredericky123** [comment]
选择对话模式，并没有地方填写prompt
还是需要一个地方填入系统级prompt，以省去每次对话的不便，期待更新

**Comment by BrianShenCC** [comment]
@fredericky123  gemini本身没有系统级prompt的设置，如果设置成第一轮对话，后续对话返回好像也不是很准确。另外你觉得是做到翻译和润色模式上，还是放在对话模式好些？


> 选择对话模式，并没有地方填写prompt 还是需要一个地方填入系统级prompt，以省去每次对话的不便，期待更新

**Comment by fredericky123** [comment]
希望就是都有呢，根据自己的提示词进行翻译和润色，目的就是自己能结合学科特色，翻译或润色的时候，能结合自己的需求给输入进去

**Comment by BrianShenCC** [comment]
好的我这两天添加一下这个功能

**Comment by fredericky123** [comment]
> 好的我这两天添加一下这个功能

谢谢呢

**Comment by BrianShenCC** [comment]
这个功能目前已经在翻译和润色模式下添加了
比如使用这个prompt 请将以下${detectFrom}内容翻译成${detectTo}：\n${text}
${detectFrom} ${detectTo} ${text}会被分别替换为来源语言的编码，目标语言的编码，和原始文本

**Comment by fredericky123** [comment]
I want you to act as an professional spelling and grammer corrector and improver. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary and improve my expression in the style of the journal Nature.
以上提示词怎么修改呢？是想用于润色

**Comment by BrianShenCC** [comment]
I want you to act as an professional spelling and grammer corrector and improver. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary and improve my expression in the style of the journal Nature. The following content is my article: \n ${text}

**Comment by fredericky123** [comment]
<img width="829" alt="image" src="https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/13982749/424550e8-0717-4dcd-b4d0-e9764de25f01">
结果没出来，能不能不显示original

**Comment by BrianShenCC** [comment]
这个估计要慢慢调prompt了，你在加上I want you to only reply the correction, the improvements and nothing else, do not write explanations.试试，现在gemini的准确率还是没有gpt好

**Comment by fredericky123** [comment]
确实 看来还是没办法用作GPT的平替
