### ISSUE TITLE
插件调用出错

### ISSUE THREAD

**Issue by Corlius** [BrianShenCC/bob-plugin-gemini-translate#16]
调用插件时提示：“接口响应错误 - 请求过于频繁，请慢一点。Gemini 对您在 API 上的请求实施速率限制。这些限制适用于每分钟 tokens 数、每分钟请求数（某些情况下是每天请求数）。当前每分钟请求60次以下免费，访问 https://ai.google.dev/pricing 了解更多信息。”
![CleanShot 2024-03-10 at 15 37 33@2x](https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/51970038/a564df38-dc18-4f1f-8590-87bec9384659)
但是使用curl命令可以正常调用API：
![CleanShot 2024-03-10 at 15 39 39@2x](https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/51970038/ca5a013d-61d6-47e6-b83a-5c3ae5053b8b)

**Comment by Corlius** [comment]
发现问题了，Google把版本号从v1改成了v1beta，修改"request.js"里的url即可
![CleanShot 2024-03-10 at 19 02 03@2x](https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/51970038/82a26770-6ca3-4077-a77d-1a3212db5284)
修改过的插件：
[bob-plugin-gemini-translate_v0.0.17.1.bobplugin.zip](https://github.com/BrianShenCC/bob-plugin-gemini-translate/files/14549885/bob-plugin-gemini-translate_v0.0.17.1.bobplugin.zip)

**Comment by BrianShenCC** [comment]
改成了v1beta

**Comment by Attiv** [comment]
今天又出现这个问题了，api 可以调用，bob 不行
