### ISSUE TITLE
gpt和OpenAI被替换成了*

### ISSUE THREAD

**Issue by Theigrams** [BrianShenCC/bob-plugin-gemini-translate#21]
在翻译时，发现翻译结果中的gpt和OpenAI都被替换成了`*`
<img width="474" alt="image" src="https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/26341831/5fa8bd5c-f7e7-4b2a-8a4d-61c0892836bf">

经过debug，发现是 `getConversation` 函数进行了替换，感觉有点影响翻译结果，是否考虑修改一下？

https://github.com/BrianShenCC/bob-plugin-gemini-translate/blob/5ae30dd506ec1ec9cbb7b66393bf5227795b39e1/src/main.js#L72C10-L72C25

**Comment by BrianShenCC** [comment]
这个是因为之前如果内容中有openai 相关的内容，请求会直接被挂掉，所以加的处理，我没有核对过现在还是否有这个限制了

**Comment by Theigrams** [comment]
现在可能没有这个限制了？我修改完后能正常使用

<img width="490" alt="image" src="https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/26341831/3c728136-3038-4077-8cb5-3d4f0fe7876d">
