### ISSUE TITLE
任何翻译结果开头都附带 <Start>

### ISSUE THREAD

**Issue by poyih** [BrianShenCC/bob-plugin-gemini-translate#22]

**Comment by poyih** [comment]
修改自定义prompt为： `translate from ${detectFrom} to ${detectTo}: ${text}` 即可

**Comment by kidcvs** [comment]
当修改自定义prompt后，划词翻译会不同情况出现不同输出：
- 比如单个单词"milestone"，就输出“里程碑 (lǐchéngbēi)”
- 比如类似“ detectFrom”，就会出现：
- 比如“ translate”，就会出现：
“Please provide me with the English text you would like me to translate into Chinese. 

For example, you could say:

"Translate: I love cats." 

Once you give me the text, I'll be happy to translate it for you! 😊”
