### ISSUE TITLE
希望版本支持0.5.0,就是直接$http.request,而不是使用stream流

### ISSUE THREAD

**Issue by chenchenfang** [BrianShenCC/bob-plugin-gemini-translate#3]
社区版本没有stream流的api.....

**Comment by BrianShenCC** [comment]
你可以使用0.0.3的版本

**Comment by chenchenfang** [comment]
一个是 info中的"minBobVersion": "1.8.0", 这个版本需要改一下

搞一个是否为stream流的选择应该就OK都兼容了

**Comment by BrianShenCC** [comment]
> 0.0.3的代码，在社区版本中似乎也有偶现无法正常返回内容的问题，暂时还没定位到原因。 解决了这个问题后我可以搞一个是否为stream流的选择，非stream流可以支持社区版本？

这个问题我也发现过，gemini有的时候会不按照正常格式返回，比如内容中包含openai。暂时没有太好的处理思路

**Comment by BrianShenCC** [comment]
> 一个是 info中的"minBobVersion": "1.8.0", 这个版本需要改一下
> 
> 搞一个是否为stream流的选择应该就OK都兼容了
支持流式请求和普通请求切换功能已经做了，可以更新一下版本
