### ISSUE TITLE
Line breaks are not handled correctly

### ISSUE THREAD

**Issue by hiuxia** [BrianShenCC/bob-plugin-gemini-translate#4]
As shown in the figure:
<img width="400" alt="image" src="https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/98009342/7b33a619-c7c8-4cf7-90ec-a9ddd7187e5c">

**Comment by hiuxia** [comment]
I tried modifying the main.js file, but it still doesn't work.
<img width="967" alt="image" src="https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/98009342/bbdb6f5f-ceb6-468c-af9b-56f22b549b02">

**Comment by BrianShenCC** [comment]
你翻译的原始文本能提供一下吗

**Comment by hiuxia** [comment]
I can not find the orginal sentence. But you can try this: He often starts with everyday materials such as push pins, seeds or pencil erasers, arranging them into larger objects that challenge viewers to question their original purpose and consider them fodder for art pieces.

**Comment by hiuxia** [comment]
<img width="400" alt="image" src="https://github.com/BrianShenCC/bob-plugin-gemini-translate/assets/98009342/3772f2e5-6997-4d18-bd35-29a61be9d39b">

**Comment by BrianShenCC** [comment]
已经解决了，可以更新一下版本

**Comment by hiuxia** [comment]
好的，感谢
