### ISSUE TITLE
反映问题

### ISSUE THREAD

**Issue by ckitty123456** [BrianShenCC/bob-plugin-gemini-translate#7]
您好，相对其他插件而言，gemini插件生成结果的速度有点慢

**Comment by BrianShenCC** [comment]
梯子的问题吧，网络原因我是处理不了的，相同网络状况我这边是比gpt 快的

**Comment by ckitty123456** [comment]
> 梯子的问题吧，网络原因我是处理不了的，相同网络状况我这边是比gpt 快的

请问调用gemini api时使用的域名是什么？我想单独把它添加到代理中

**Comment by BrianShenCC** [comment]
https://generativelanguage.googleapis.com/
