### ISSUE TITLE
使用插件的对话模式时，返回：* GenerateContentRequest.contents[1].parts[0].data: required oneof field 'data' must have one initialized field 或者 Bad Request

### ISSUE THREAD

**Issue by fuarthur** [BrianShenCC/bob-plugin-gemini-translate#8]
我尝试在 bob 的服务中同时添加本插件的翻译模式和对话模式，翻译模式可以正常显示结果，但对话模式会返回：* GenerateContentRequest.contents[1].parts[0].data: required oneof field 'data' must have one initialized field或者 Bad Request.

**Comment by BrianShenCC** [comment]
对话模式如果是提示Bad Request的话可能是由于上一轮对话没有完全返回，gemini本身的对话处理并不是特别好，只能接受一来一回的对话，不能一个人连续说几句，这时需要使用#clear清空对话。 这个错误明天会在返回信息里面提示出来

另一种情况暂时没有复现出来
