### ISSUE TITLE
支持自定义域名

### ISSUE THREAD

**Issue by vfasky** [BrianShenCC/bob-plugin-gemini-translate#9]
希望支持自定义域名，让使用 https://github.com/tsui66/bard-proxy  代理的同学可以 无缝访问。

**Comment by BrianShenCC** [comment]
已支持，但是用你这个的代理似乎不支持流式返回，他会把整个流直接返回成一个json，造成跟原来返回的格式不一致

**Comment by vfasky** [comment]
我修改下，https://github.com/vfasky/bard-proxy 支持流式返回

**Comment by BrianShenCC** [comment]
不错确实可以用了
